<?php

namespace ProcessWire;

/**
 * PWCommerce: WeightsAndMeasures
 *
 * Class to handle Weights And Measures for PWCommerce general use.
 *
 * @author Francis Otieno (Kongondo) <kongondo@gmail.com> kongondo.com
 *
 *
 *
 * PWCommerceWeightsAndMeasures for PWCommerce
 * Copyright (C) 2025 by Francis Otieno
 * MIT License
 *
 */

class PWCommerceWeightsAndMeasures extends WireData
{

	/**
	 * Returns array of weights and measures, metric and imperial.
	 *
	 * @return mixed
	 */
	public function getWeightsAndMeasures() {
		$weightsAndMeasures = [
			[
				'id' => 1,
				'name' => __('millimetre'),
				'abbreviation' => 'mm',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 2,
				'name' => __('centimetre'),
				'abbreviation' => 'cm',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 3,
				'name' => __('decimetre'),
				'abbreviation' => 'dm',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 4,
				'name' => __('metre'),
				'abbreviation' => 'm',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 5,
				'name' => __('decametre'),
				'abbreviation' => 'dam',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 6,
				'name' => __('kilometre'),
				'abbreviation' => 'km',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 7,
				'name' => __('inch'),
				'abbreviation' => 'in',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 8,
				'name' => __('foot'),
				'abbreviation' => 'ft',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 9,
				'name' => __('yard'),
				'abbreviation' => 'yd',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 10,
				'name' => __('rod'),
				'abbreviation' => 'rd',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'linear',
			],
			[
				'id' => 11,
				'name' => __('furlong'),
				'abbreviation' => 'fur',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'linear',
			],
			[
				'id' => 12,
				'name' => __('mile'),
				'abbreviation' => 'mi',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'linear',
			],
			[
				'id' => 13,
				'name' => __('fathom'),
				'abbreviation' => 'ftm',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'linear',
			],
			[
				'id' => 14,
				'name' => __('nautical mile'),
				'abbreviation' => 'nmi',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'linear',
			],
			[
				'id' => 15,
				'name' => __('square centimetre'),
				'abbreviation' => 'cm2',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 16,
				'name' => __('square decimetre'),
				'abbreviation' => 'dm2',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 17,
				'name' => __('square metre'),
				'abbreviation' => 'm2',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 18,
				'name' => __('are'),
				'abbreviation' => 'a',
				'type' => 'metric',
				'sub_type' => 'uncommon',
				'dimension' => 'area',
			],
			[
				'id' => 19,
				'name' => __('hectare'),
				'abbreviation' => 'ha',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 20,
				'name' => __('square kilometre'),
				'abbreviation' => 'km2',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 21,
				'name' => __('square inch'),
				'abbreviation' => 'in2',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 22,
				'name' => __('square foot'),
				'abbreviation' => 'ft2',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 23,
				'name' => __('square yard'),
				'abbreviation' => 'yd2',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 24,
				'name' => __('square rod'),
				'abbreviation' => 'rd2',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 25,
				'name' => __('acre'),
				'abbreviation' => 'ac',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 26,
				'name' => __('square mile'),
				'abbreviation' => 'm2',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'area',
			],
			[
				'id' => 27,
				'name' => __('cubic centimetre'),
				'abbreviation' => 'cm3',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 28,
				'name' => __('cubic decimetre'),
				'abbreviation' => 'dm3',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 29,
				'name' => __('cubic metre'),
				'abbreviation' => 'm3',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 30,
				'name' => __('millilitre'),
				'abbreviation' => 'ml',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 31,
				'name' => __('centilitre'),
				'abbreviation' => 'cl',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 32,
				'name' => __('decilitre'),
				'abbreviation' => 'dl',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 33,
				'name' => __('litre'),
				'abbreviation' => 'l',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 34,
				'name' => __('dekalitre'),
				'abbreviation' => 'dal',
				'type' => 'metric',
				'sub_type' => 'uncommon',
				'dimension' => 'volume',
			],
			[
				'id' => 35,
				'name' => __('hectolitre'),
				'abbreviation' => 'hl',
				'type' => 'metric',
				'sub_type' => 'uncommon',
				'dimension' => 'volume',
			],
			[
				'id' => 36,
				'name' => __('cubic inch'),
				'abbreviation' => 'cu.in',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 37,
				'name' => __('cubic foot'),
				'abbreviation' => 'cu. ft',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 38,
				'name' => __('cubic yard'),
				'abbreviation' => 'cu.yd',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 39,
				'name' => __('U.S. fluid ounce'),
				'abbreviation' => 'fl.oz',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 40,
				'name' => __('British imperial fluid ounce'),
				'abbreviation' => 'fl.oz (imp)',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'volume',
			],
			[
				'id' => 41,
				'name' => __('pint'),
				'abbreviation' => 'pt',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 42,
				'name' => __('quart'),
				'abbreviation' => 'qt',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 43,
				'name' => __('U.S. gallon'),
				'abbreviation' => 'gal',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'volume',
			],
			[
				'id' => 44,
				'name' => __('imperial gallon'),
				'abbreviation' => 'gal (imp)',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'volume',
			],
			[
				'id' => 45,
				'name' => __('dry pint'),
				'abbreviation' => 'pt (dry)',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'volume',
			],
			[
				'id' => 46,
				'name' => __('dry quart'),
				'abbreviation' => 'qt (dry)',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'volume',
			],
			[
				'id' => 47,
				'name' => __('peck'),
				'abbreviation' => 'pk',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'volume',
			],
			[
				'id' => 48,
				'name' => __('U.S. bushel'),
				'abbreviation' => 'bu',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'volume',
			],
			[
				'id' => 49,
				'name' => __('imperial bushel'),
				'abbreviation' => 'bu (imp)',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'volume',
			],
			[
				'id' => 50,
				'name' => __('milligram'),
				'abbreviation' => 'mg',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'weight',
			],
			[
				'id' => 51,
				'name' => __('centigram'),
				'abbreviation' => 'cg',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'weight',
			],
			[
				'id' => 52,
				'name' => __('decigram'),
				'abbreviation' => 'dg',
				'type' => 'metric',
				'sub_type' => 'uncommon',
				'dimension' => 'weight',
			],
			[
				'id' => 53,
				'name' => __('gram'),
				'abbreviation' => 'g',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'weight',
			],
			[
				'id' => 54,
				'name' => __('dekagram'),
				'abbreviation' => 'dag',
				'type' => 'metric',
				'sub_type' => 'uncommon',
				'dimension' => 'weight',
			],
			[
				'id' => 55,
				'name' => __('hectogram'),
				'abbreviation' => 'hg',
				'type' => 'metric',
				'sub_type' => 'uncommon',
				'dimension' => 'weight',
			],
			[
				'id' => 56,
				'name' => __('kilogram'),
				'abbreviation' => 'kg',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'weight',
			],
			[
				'id' => 57,
				'name' => __('metric ton'),
				'abbreviation' => 't',
				'type' => 'metric',
				'sub_type' => 'common',
				'dimension' => 'weight',
			],
			[
				'id' => 58,
				'name' => __('grain'),
				'abbreviation' => 'gr',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'weight',
			],
			[
				'id' => 59,
				'name' => __('dram'),
				'abbreviation' => 'dr',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'weight',
			],
			[
				'id' => 60,
				'name' => __('ounce'),
				'abbreviation' => 'oz',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'weight',
			],
			[
				'id' => 61,
				'name' => __('pound'),
				'abbreviation' => 'lb',
				'type' => 'imperial',
				'sub_type' => 'common',
				'dimension' => 'weight',
			],
			[
				'id' => 62,
				'name' => __('short hundredweight'),
				'abbreviation' => 'cwt',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'weight',
			],
			[
				'id' => 63,
				'name' => __('long hundredweight'),
				'abbreviation' => 'lcwt',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'weight',
			],
			[
				'id' => 64,
				'name' => __('short ton'),
				'abbreviation' => 'T',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'weight',
			],
			[
				'id' => 65,
				'name' => __('long ton '),
				'abbreviation' => 'long tn',
				'type' => 'imperial',
				'sub_type' => 'uncommon',
				'dimension' => 'weight',
			],
		];
		//---------------
		return $weightsAndMeasures;
	}
}
